const booksData = [
    {
        id: "echoes-eternity",
        title: "Echoes of Eternity",
        author: "Sabirkhan Pathan",
        image: "images/story-horror.png",
        category: "mystery",
        info: "A journey through time and space.",
        originalPrice: 499,
        discountPercent: 40,
        rating: 4.8,
        reviewsCount: 124,
        description: "In a world where time is currency, one man discovers a way to bankrupt the system. 'Echoes of Eternity' is a gripping sci-fi thriller that challenges our perception of reality. Written by Sabirkhan Pathan, this bestseller has captivated readers worldwide.",
        reviews: [
            { user: "Ali K.", text: "Absolutely mind-bending!", rating: 5 },
            { user: "Sara M.", text: "Couldn't put it down.", rating: 5 }
        ]
    },
    {
        id: "silent-scream",
        title: "The Silent Scream",
        author: "Sabirkhan Pathan",
        image: "images/story-romance.png",
        category: "mystery",
        info: "A mystery that will keep you awake.",
        originalPrice: 399,
        discountPercent: 25,
        rating: 4.5,
        reviewsCount: 89,
        description: "When a famous singer loses her voice, Detective Ray discovers it wasn't an accident. A tale of jealousy, betrayal, and sound.",
        reviews: [
            { user: "John D.", text: "Great mystery.", rating: 4 }
        ]
    },
    {
        id: "golden-bird",
        title: "The Golden Bird",
        author: "Sabirkhan Pathan",
        image: "images/audio-gold.png",
        category: "drama",
        info: "A folklore retold for the modern age.",
        originalPrice: 599,
        discountPercent: 50,
        rating: 4.9,
        reviewsCount: 205,
        description: "The classic tale reimagined in a cyberpunk universe. Follow the Golden Bird as it hacks into the corporate mainframe.",
        reviews: []
    },
    {
        id: "desert-rose",
        title: "Desert Rose",
        author: "Sabirkhan Pathan",
        image: "images/audio-rain.png",
        category: "emotional",
        info: "Romance amidst the dunes.",
        originalPrice: 299,
        discountPercent: 10,
        rating: 4.2,
        reviewsCount: 50,
        description: "Love blooms in the harshest of places. A historical romance set in 18th century Rajasthan.",
        reviews: []
    },
    {
        id: "ocean-depths",
        title: "Ocean Depths",
        author: "Sabirkhan Pathan",
        image: "images/audio-train.png",
        category: "mystery",
        info: "What lies beneath?",
        originalPrice: 450,
        discountPercent: 30,
        rating: 4.6,
        reviewsCount: 110,
        description: "Deep sea exploration goes wrong when the crew encounters a civilization that shouldn't exist.",
        reviews: []
    },
    {
        id: "urban-jungle",
        title: "Urban Jungle",
        author: "Sabirkhan Pathan",
        image: "images/story-horror.png",
        category: "drama",
        info: "Survival in the concrete city.",
        originalPrice: 350,
        discountPercent: 20,
        rating: 4.3,
        reviewsCount: 75,
        description: "A gritty look at life in the megalopolis of 2050.",
        reviews: []
    },
    {
        id: "forgotten-realms",
        title: "Forgotten Realms",
        author: "Sabirkhan Pathan",
        image: "images/story-romance.png",
        category: "drama",
        info: "Fantasy epic.",
        originalPrice: 799,
        discountPercent: 60,
        rating: 4.7,
        reviewsCount: 300,
        description: "Dragons are gone, but their magic remains. A young mage must find the lost spell.",
        reviews: []
    },
    {
        id: "digital-ghost",
        title: "Digital Ghost",
        author: "Sabirkhan Pathan",
        image: "images/audio-gold.png",
        category: "mystery",
        info: "Cybercrime thriller.",
        originalPrice: 550,
        discountPercent: 35,
        rating: 4.4,
        reviewsCount: 95,
        description: "Someone is deleting people from the government database. Literally.",
        reviews: []
    },
    {
        id: "last-letter",
        title: "The Last Letter",
        author: "Sabirkhan Pathan",
        image: "images/audio-rain.png",
        category: "emotional",
        info: "Emotional drama.",
        originalPrice: 250,
        discountPercent: 15,
        rating: 4.8,
        reviewsCount: 150,
        description: "A soldier's letter arrives 50 years late.",
        reviews: []
    },
    {
        id: "quantum-leap",
        title: "Quantum Leap",
        author: "Sabirkhan Pathan",
        image: "images/audio-train.png",
        category: "mystery",
        info: "Science fiction adventure.",
        originalPrice: 650,
        discountPercent: 45,
        rating: 4.6,
        reviewsCount: 180,
        description: "Jumping dimensions was meant to be safe. It wasn't.",
        reviews: []
    }
];
